### ISSUE TITLE
Great extension! Thank you!

### ISSUE THREAD

**Issue by SalocinDotTEN** [bizley-code/Yii-MultiMailer#1]
Hi!

My company had a big issue with the server provider suddenly switching off the mail() function, causing the Yii 1.1 sites to stop sending out email from the contact forms.

Your extension has been a life saver for us!

I can't thank you enough for this!  :)

**Comment by bizley** [comment]
I'm so glad to hear this :)
I have switched to Yii 2 and this is why this extension is left behind a bit (PHPMailer is 5.2.13 now and we got 5.2.10) but it is great to know that it is still useful.
